### PR TITLE
Start ubxdlinks for w/c 27th July 2015

### PR DESCRIPTION
**Pull request by h-lame**
Assume the date needs to be the publication date, which I want to be 14:30 on Friday and as it's in UTC it needs to be 13:30.  I think?

### CODE REVIEW

**Comment by h-lame** [comment]
Oh! Autobuild and deploy from branches is cool, but a bit unexpected that my branch is now what's deployed to gh pages.

**Comment by tomsabin** [comment]
@h-lame yep sorry, still working on all of the blog workflow so nothing is quite ready (and as you say all branches push to `gh-pages`).

We are considering using prose.io as the content editor as it'll make producing the frontmatter much easier to produce when we know what we need (you can view your article at http://prose.io/#unboxed/ubxd_blog_refresh/edit/roundup-wc-july-27th/source/blog/unboxed-roundup-our-links-for-w-c-27th-july-2015.md).

I had reverted the version mentioned last week to you, so a lot of the functionality there isn't working now: tags, published/unpublished states, author.

It would be interesting to see what your preferred workflow would be - working on a pull request like this to eventually build up the blog post. Or to commit directly to master (using prose) on an unpublished blog and then turn on publishing when you've finished.

**Comment by h-lame** [comment]
@tomsabin I'd rather just use GH because I'm not that bothered about seeing what the post will look like (although if we could have branches being built and deployed somewhere separate that would be awesome).  Also I'm wary of the GH permissions model and prose.io wanting commit on every repo I have access to.

**Comment by h-lame** [comment]
Certainly for the roundups I'd want to do it in a PR that I merge (or work out how to merge automatically) at the correct time for deployment - don't want a draft post going out to the world before it's ready.

**Comment by h-lame** [comment]
It's Firday 14:30 (ish).  Time to merge!

**Pull request merged**
